FROM node:latest as build-stage
WORKDIR /app
COPY package*.json ./
RUN export PYTHONUNBUFFERED=1
RUN apk --no-cache add build-base
RUN apk add --update --no-cache python3 \
  && ln -sf python3 /usr/bin/python \
  && python3 -m ensurepip \
  && pip3 install --no-cache --upgrade pip setuptools
  
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
